Cleanup this garbage
labdiscord/statcord.py pull request #21
Opened 2021-02-19 14:12 UTC by Iapetus-11

Exactly what it sounds like. Minor-ish changes that shouldn't break anything but improve your code. Don't do what you did last time and ignore my pr for a week until it's outdated.

2021-02-19 18:42 UTC, anishanne requested changes

2021-02-19 18:42 UTC, anishanne commented on statcord/client.py
>          self.logging_level = kwargs.get("logging_level", logging.WARNING)
"Kwargs" is not defined and causes the library to crash.

2021-02-19 20:30 UTC, anishanne requested changes

2021-02-19 20:30 UTC, anishanne commented on statcord/client.py
>          self.custom1: Optional[Coroutine] = custom1
Custom1 + Custom2 are undefined.

2021-02-20 00:02 UTC, anishanne requested changes

2021-02-20 00:02 UTC, anishanne commented on statcord/client.py
> +            raise TypeError(
This formatting is unnecessary.

2021-02-20 00:31 UTC, tbnritzdoge commented
i like garbage 😃

2021-03-26 03:32 UTC, closed without merging